apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: d
  namespace: mexample
  labels:
    name: d
    namespace: mexample
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: d
        namespace: mexample
    spec:
      containers:
      - name: d
        image: eu.gcr.io/massive-plasma-161616/d:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
