apiVersion: v1
kind: Service
metadata:
  name: e
  namespace: mexample
  labels:
    service-type: http-endpoint
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  type: ClusterIP #LoadBalancer
  selector:
    name: e
